language: java
jdk:
- oraclejdk8
script:
- mvn javadoc:javadoc 
deploy:
  provider: releases
  api-key: $GITHUB_API_TOKEN
  file_glob: true
  file: docs/*
  skip_cleanup: true
  on:
    branch: master